# Generated by Django 2.2.12 on 2020-06-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_app', '0005_auto_20200626_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
