# Generated by Django 2.2.12 on 2020-06-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_app', '0006_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacao',
            field=models.CharField(max_length=100),
        ),
    ]
