# Generated by Django 2.2.12 on 2020-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_app', '0008_auto_20200627_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSSH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('nome_usuario', models.EmailField(max_length=254)),
                ('home', models.CharField(max_length=50)),
            ],
        ),
    ]
